#version: '3.8'

services:
  client:
    build:
      context: ./vueapp.client
      dockerfile: Dockerfile
    container_name: vue_client
    ports:
      - "8081:80" # Host port 8081 → Vue container's port 80
    networks:
      - app_network
    depends_on:
      - server

  server:
    build:
      context: ./VueApp.Server
      dockerfile: Dockerfile
    container_name: dotnet_server
    ports:
      - "8180:8180" # Host port 8180 → .NET app port 8180
    networks:
      - app_network
    environment:
      - ASPNETCORE_URLS=http://+:8180
      - ASPNETCORE_ENVIRONMENT=Production

networks:
  app_network:
    driver: bridge
