name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: action/setup-node@v2
      with: 
        node-version: 22
    - uses: keita-hino/vue-tsc-action@main

    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vueapp:$(date +%s)
